Repetitions/2022-12-27/final/westcoast-cars/Models/VehicleModel.cs
namespace westcoast_cars.Models;

public class VehicleModel
{
    public int Id { get; set; }
    public string RegistrationNumber { get; set; } = "";
    public string VinNumber { get; set; } = "";
    public string Manufacturer { get; set; } = "";
    public string Model { get; set; } = "";
    public string ModelYear { get; set; } = "";
    public int Mileage { get; set; }
}

Repetitions/2022-12-27/final/westcoast-cars/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;

namespace westcoast_cars.Controllers;

public class HomeController : Controller
{
    public IActionResult Index()
    {
        return View();
    }
}

Repetitions/2022-12-27/final/westcoast-cars/Controllers/VehiclesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using westcoast_cars.Data;
using westcoast_cars.Models;

namespace westcoast_cars.Controllers;

[Route("vehicles")]
public class VehiclesController : Controller
{
    private readonly WestcoastCarsContext _context;
    public VehiclesController(WestcoastCarsContext context)
    {
        _context = context;
    }

    public async Task<IActionResult> Index()
    {
        var vehicles = await _context.Vehicles.ToListAsync();
        return View("Index", vehicles);
    }

    [Route("details/{vehicleId}")]
    public async Task<IActionResult> Details(int vehicleId)
    {
        var model = await _context.Vehicles.FirstOrDefaultAsync(c => c.Id == vehicleId);

        return View("Details", model);
    }

    [HttpGet("create")]
    public IActionResult Create()
    {
        var vehicle = new VehicleModel();
        return View("Create", vehicle);
    }

    [HttpPost("create")]
    public async Task<IActionResult> Create(VehicleModel vehicleModel)
    {
        _context.Vehicles.Add(vehicleModel);
        if (await _context.SaveChangesAsync() > 0)
        {
            return RedirectToAction(nameof(Index));
        }
        else
        {
            var vehicle = new VehicleModel();
            return View("Create", vehicle);
        }
    }
}

Repetitions/2022-12-27/final/westcoast-cars/Views/Vehicles/Create.cshtml
@model westcoast_cars.Models.VehicleModel

<form asp-action="create" asp-controller="vehicles" method="post">
    <input placeholder="RegistrationNumber" asp-for="RegistrationNumber" /><br>
    <input placeholder="Manufacturer" asp-for="Manufacturer" /><br>
    <input placeholder="Model" asp-for="Model" /><br>
    <input type="submit" value="Save" />
</form>

Repetitions/2022-12-27/final/westcoast-cars/Views/Vehicles/Details.cshtml
@model westcoast_cars.Models.VehicleModel

@{
    ViewBag.PageTitle = "Information";
}
<h1>Detaljer om bilen</h1>
<h2>@Model.Id - @Model.Manufacturer - @Model.Model</h2>

Repetitions/2022-12-27/final/westcoast-cars/Views/Vehicles/Index.cshtml
@model IList<westcoast_cars.Models.VehicleModel>
<h1>Bilar i lager</h1>

<div>
    <a asp-action="Create" asp-controller="Vehicles">Create new vehicle</a>

</div>
<br>
@foreach (var vehicle in Model)
{
    <a asp-action="Details" asp-controller="Vehicles" asp-route-vehicleId=@vehicle.Id>
    @vehicle.Manufacturer - @vehicle.Model
</a><br>
}