Structure our code/final/westcoast-cars.web/Controllers/UsersAdminController.cs
using Microsoft.AspNetCore.Mvc;
using westcoast_cars.web.Interfaces;
using westcoast_cars.web.Models;
using westcoast_cars.web.ViewModels.Users;

namespace westcoast_cars.web.Controllers;

[Route("users/admin")]
public class UsersAdminController : Controller
{
    private readonly IUnitOfWork _unitOfWork;
    public UsersAdminController(IUnitOfWork unitOfWork)
    {
        _unitOfWork = unitOfWork;

    }

    public async Task<IActionResult> Index()
    {
        var result = await _unitOfWork.UserRepository.ListAllAsync();
        var users = result.Select(u => new UsersListViewModel
        {
            UserId = u.UserId,
            UserName = u.UserName,
            FirstName = u.FirstName,
            LastName = u.LastName,
            Email = u.Email
        }).ToList();

        return View("Index", users);
    }

    [HttpGet("create")]
    public IActionResult Create()
    {
        var user = new UserPostViewModel();
        return View("Create", user);
    }

    [HttpPost("create")]
    public async Task<IActionResult> Create(UserPostViewModel user)
    {
        if (!ModelState.IsValid) return View("Create", user);

        if (await _unitOfWork.UserRepository.FindByEmailAsync(user.Email) is not null)
        {
            var error = new ErrorModel
            {
                ErrorTitle = "Användare finns redan",
                ErrorMessage = $"Användare med e-post {user.Email} finns redan upplagd!"
            };
            return View("_Error", error);
        }

        var userToAdd = new UserModel
        {
            UserName = user.UserName,
            FirstName = user.FirstName,
            LastName = user.LastName,
            Email = user.Email,
            Password = user.Password
        };

        if (await _unitOfWork.UserRepository.AddAsync(userToAdd))
        {
            if (await _unitOfWork.Complete())
            {
                return RedirectToAction(nameof(Index));
            }
        }

        return View("_Error", new ErrorModel { ErrorTitle = "Gick inte att spara användare", ErrorMessage = $"Ett fel inträffade när användare {user.FirstName} {user.LastName} skulle sparas" });
    }

    [HttpGet("edit/{userId}")]
    public async Task<IActionResult> Edit(int userId)
    {

        var result = await _unitOfWork.UserRepository.FindByIdAsync(userId);

        if (result is null)
        {
            return View("_Error", new ErrorModel { ErrorTitle = "Kunde inte hitta användare", ErrorMessage = $"Vi kunde inte hitta någon användare med id {userId}" });
        }

        var userToUpdate = new UserUpdateViewModel
        {
            UserId = result.UserId,
            UserName = result.UserName,
            FirstName = result.FirstName,
            LastName = result.LastName,
            Email = result.Email
        };

        return View("Edit", userToUpdate);
    }

    [HttpPost("edit/{userId}")]
    public async Task<IActionResult> Edit(int userId, UserUpdateViewModel user)
    {
        try
        {
            if (!ModelState.IsValid) return View("Edit", user);

            var userToUpdate = await _unitOfWork.UserRepository.FindByIdAsync(userId);

            if (userToUpdate is null)
            {
                var notFoundError = new ErrorModel
                {
                    ErrorTitle = "Användare saknas!",
                    ErrorMessage = $"Det gick inte att hitta användaren {user.FirstName} {user.LastName}"
                };

                return View("_Error", notFoundError);
            }

            userToUpdate.UserName = user.UserName;
            userToUpdate.FirstName = user.FirstName;
            userToUpdate.LastName = user.LastName;
            userToUpdate.Email = user.Email;

            if (await _unitOfWork.UserRepository.UpdateAsync(userToUpdate))
            {
                if (await _unitOfWork.Complete())
                {
                    return RedirectToAction(nameof(Index));
                }
            }

            return View("_Error", new ErrorModel { ErrorTitle = "Ett fel inträffade", ErrorMessage = "Något gick fel när användaren skulle uppdateras" });
        }
        catch (Exception ex)
        {
            return View("_Error", new ErrorModel { ErrorTitle = "Ett fel har inträffat", ErrorMessage = ex.Message });
        }
    }

    [Route("delete/{userId}")]
    public async Task<IActionResult> Delete(int userId)
    {
        try
        {
            var userToDelete = await _unitOfWork.UserRepository.FindByIdAsync(userId);

            if (userToDelete is null) return RedirectToAction(nameof(Index));

            if (await _unitOfWork.UserRepository.DeleteAsync(userToDelete))
            {
                if (await _unitOfWork.Complete())
                {
                    return RedirectToAction(nameof(Index));
                }
            }

            return View("_Error", new ErrorModel { ErrorTitle = "Ett fel inträffade när användaren skulle tas bort", ErrorMessage = $"Ett fel inträffade när användare med id {userId} skulle raderas" });
        }
        catch (Exception ex)
        {
            return View("_Error", new ErrorModel { ErrorTitle = "Ett fel har inträffat", ErrorMessage = ex.Message });
        }
    }

}

Structure our code/final/westcoast-cars.web/Views/UsersAdmin/Create.cshtml
@model westcoast_cars.web.ViewModels.Users.UserPostViewModel

@{
    Layout = "_LayoutAdmin";
}

<section class="page">
    <h1 class="page-title">Lägg till användare</h1>
    <form class="shadow" asp-action="create" asp-controller="UsersAdmin" method="post">
        <div class="form-control">
            <label asp-for="UserName"></label>
            <input asp-for="UserName" />
            <span class="error" asp-validation-for="UserName"></span>
        </div>
        <div class="form-control">
            <label asp-for="FirstName"></label>
            <input asp-for="FirstName" />
            <span class="error" asp-validation-for="FirstName"></span>
        </div>
        <div class="form-control">
            <label asp-for="LastName"></label>
            <input asp-for="LastName" />
            <span class="error" asp-validation-for="LastName"></span>
        </div>
        <div class="form-control">
            <label asp-for="Email"></label>
            <input asp-for="Email" />
            <span class="error" asp-validation-for="Email"></span>
        </div>
        <div class="form-control">
            <label asp-for="Password"></label>
            <input asp-for="Password" />
            <span class="error" asp-validation-for="Password"></span>
        </div>
        <div class="form-control">
            <div class="buttons-container">
                <button type="Submit" class="btn btn-primary"><i class="fa-sharp fa-solid fa-floppy-disk"></i>
                    Spara</button>
                <a asp-action="index" asp-controller="UsersAdmin" class="btn btn-warning"><i
                        class="fa-solid fa-arrow-left"></i> Avbryt</a>
            </div>
        </div>
    </form>
</section>

Structure our code/final/westcoast-cars.web/Views/UsersAdmin/Edit.cshtml
@model westcoast_cars.web.ViewModels.Users.UserUpdateViewModel

@{
    Layout = "_LayoutAdmin";
}

<section class="page">
    <h1 class="page-title">Uppdatera användare</h1>
    <form class="shadow" asp-action="edit" asp-controller="UsersAdmin" asp-route-userId=@Model.UserId method="post">
        <div class="form-control">
            <label asp-for="UserName"></label>
            <input asp-for="UserName" />
            <span class="error" asp-validation-for="UserName"></span>
        </div>
        <div class="form-control">
            <label asp-for="FirstName"></label>
            <input asp-for="FirstName" />
            <span class="error" asp-validation-for="FirstName"></span>
        </div>
        <div class="form-control">
            <label asp-for="LastName"></label>
            <input asp-for="LastName" />
            <span class="error" asp-validation-for="LastName"></span>
        </div>
        <div class="form-control">
            <label asp-for="Email"></label>
            <input asp-for="Email" />
            <span class="error" asp-validation-for="Email"></span>
        </div>
        <div class="form-control">
            <label asp-for="Password"></label>
            <input disabled asp-for="Password" />
            <span class="error" asp-validation-for="Password"></span>
        </div>
        <div class="form-control">
            <div class="buttons-container">
                <button type="Submit" class="btn btn-primary"><i class="fa-sharp fa-solid fa-floppy-disk"></i>
                    Spara</button>
                <a asp-action="index" asp-controller="UsersAdmin" class="btn btn-warning"><i
                        class="fa-solid fa-arrow-left"></i> Avbryt</a>
            </div>
        </div>
    </form>
</section>

Structure our code/final/westcoast-cars.web/Views/UsersAdmin/Index.cshtml
@model IList<westcoast_cars.web.ViewModels.Users.UsersListViewModel>
@{
    Layout = "_LayoutAdmin";
}

<section class="page">
    <h1>Användare</h1>
    <div class="table-container">
        <div>
            <a class="btn btn-primary" asp-action="create" asp-controller="UsersAdmin">Lägg till ny användare</a>
        </div>
        <table>
            <thead>
                <tr>
                    <th></th>
                    <th>Användarnamn</th>
                    <th>Förnamn</th>
                    <th>Efternamn</th>
                    <th>E-Post</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var user in Model)
                {
                    <tr>
                        <td>
                            <a class="edit-icon" asp-action="Edit" asp-controller="UsersAdmin"
                            asp-route-userId=@user.UserId><i class="fa-regular fa-pen"></i></a>
                        </td>
                        <td>@user.UserName</td>
                        <td>@user.FirstName</td>
                        <td>@user.LastName</td>
                        <td>@user.Email</td>
                        <td><a class="delete-icon" asp-action="Delete" asp-controller="UsersAdmin"
                            asp-route-userId=@user.UserId><i class="fa-solid fa-trash-can"></i></a></td>
                    </tr>
                }
            </tbody>
            <tfoot>
                <tr>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                </tr>
            </tfoot>
        </table>
    </div>
</section>